name: adhan_times
description: A simple app for adhan times.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  flutter_spinkit: ^4.1.2+1
flutter_icons:
  image_path: "icon/ramadan2.png" 
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
  - images/

